### ISSUE TITLE
Give us an update

### ISSUE THREAD

**Issue by MineTurtlee** [loyahdev/certificates#1]
Please, it’s been a week and no updated info about certificates?

**Comment by loyahdev** [comment]
Hi! @MineTurtlee all of the Certitficates accessible on my website are all up to date and I add new ones as soon as they come out. I'm sorry that there isnt currently any new ones at the moment.

**Comment by MineTurtlee** [comment]
> Hi! @MineTurtlee all of the Certitficates accessible on my website are all up to date and I add new ones as soon as they come out. I'm sorry that there isnt currently any new ones at the moment.

Hey! @loyahdev how to do FluxSign?

**Comment by loyahdev** [comment]
> > Hi! @MineTurtlee all of the Certitficates accessible on my website are all up to date and I add new ones as soon as they come out. I'm sorry that there isnt currently any new ones at the moment.
> 
> Hey! @loyahdev how to do FluxSign?

Hello! FluxSign is a dead project I had as an iPA Signer and I've removed its references from this repository.
